name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Update Pipeline
        working-directory: /home/pi/esp-idf
        run: |
          git pull
          git submodule update
          /home/pi/esp-idf/install.sh
      - name: Build Latest Commit
        run: |
          . /home/pi/esp-idf/export.sh
          idf.py app
        
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
