name: Build workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build latest commit
          run: |
            . ~/esp-idf/export.sh
            idf.py app
        
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
